export default {
  CHECK_VERIFICATION_CODE: 'CHECK_VERIFICATION_CODE',
  CONFIRM_CODE_SENT: 'CONFIRM_CODE_SENT',
  CONFIRM_CODE_VERIFICATION: 'CONFIRM_CODE_VERIFICATION',
  INIT_PHONE_SIGNIN: 'INIT_PHONE_SIGNIN',
  TOGGLE_LOADING: 'TOGGLE_LOADING',
}
